### PR TITLE
MPI config, conda env

### PR DESCRIPTION
**Pull request by Eothred**
Some config stuff we have on our ESS main branch

### CODE REVIEW

**Comment by KonradAltenmueller** [comment]
Hello!
In case this pull request was forgotten, I was not able to install pyorbit manually from the collaboration main branch, while the ESS one works fine, so probably it would be good to merge it.
Thanks a lot!

**Comment by juanfem** [comment]
closing and following up on #6

**Comment by juanfem** [comment]
Reopening because we decided to work on forks

**Comment by azukov** [comment]
@juanfem @Eothred 
Can we close this one?

**Comment by Eothred** [comment]
I support merging, but I take no responsibility for the OSX parts :penguin:

**Comment by juanfem** [comment]
yes, I close it

**Pull request closed without merging**
