### PR TITLE
Meson build

### PR DESCRIPTION
**Pull request by Eothred**
Work mainly by Sasha and a little fix from me. This is checked to work for one flavour of Linux, and OSX.

I think this is mature enough that we can start discussing and review for a potential merge.

### CODE REVIEW

**Comment by Eothred** [comment]
Cleared some system config stuff and now it compiles without issues also on CentOS.

**Comment by azukov** [comment]
I think CentOS works fine. The only stuff left is to allow command line key to specify fftw, mpi and python headers/libraries.
For Mac it will be /opt/homebrew etc

**Comment by Eothred** [comment]
- [x] fftw, see line 15 of src/meson.build
- [x] python headers, see line 213 of src/meson.build
- [ ] mpi, still open

**Comment by Eothred** [comment]
Aaaah, ok I understand now. Juan used anaconda to install, I forget that there are many common ways to Rome on OSX.

Fully agreed, homebrew is still quite popular. I don't have OSX myself though so I will not be of much help.

**Comment by Eothred** [comment]
Did you try to set HOMEBREW_PREFIX? [This seems relevant](https://github.com/mesonbuild/meson/pull/12170)

**Comment by juanfem** [comment]
I've just tested building the meson build on a MacBook M1 installing **fftw** and **mpich** using homebrew instead of conda. It builds successfully when setting the env vars that Yngve suggested.

In order to install fftw and mpich using homebrew one needs to do a little trick, because homebrew will install open-mpi as a dependency of fftw, even though it works fine with mpich. The steps are:
```
$ brew install fftw
$ brew unlink open-mpi
$ brew install mpich
```

Then one needs to set the env vars:
```
$ export CPATH="$CPATH:$(brew --prefix)/include"
$ export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"
```
Alternatively, one can add the libraries path to LDFLAGS instead of to LIBRARY_PATH
```
$ export CPATH="$CPATH:$(brew --prefix)/include"
$ export LDFLAGS="-L/$(brew --prefix)/lib"
```

I suggest we add this instructions to the README and then the PR can be merged.

**Comment by azukov** [comment]
Apparently none of the above needed as long as meson can locate **pkg-config**
so the following lines install everything that is needed for non-MPI version
```bash
brew install pkg-config fftw
brew list
```
The result of this command (in  fresh homebrew installation)
```
==> Formulae
ca-certificates	gcc		hwloc		libevent	lz4		open-mpi	pkg-config	xz
fftw		gmp		isl		libmpc		mpfr		openssl@3	pmix		zstd
```
As long as **homebrew/bin** is in the $PATH nothing else is needed.

**Comment by Eothred** [comment]
Thanks both for investigating. That sounds quite encouraging Sasha, I think a simple instruction to install pkg-config is quite straight forward?

**Comment by azukov** [comment]
I think this one is ready. 
* Uses meson build
* Tested different platform, pip/conda/Linux/MacOS
* Cleaned up dependencies
* Not building MPI version yet
* The package name is PyORBIT and automated versioning with setuptools-scm is back.

**Review by shishlo — APPROVED** [review]
Great!

**Review by juanfem — APPROVED** [review]
looks good!

**Pull request merged**
