### PR TITLE
Sync latest changes in the python2 version

### PR DESCRIPTION
**Pull request by juanfem**
This PR adds all the latest changes implemented in the Python 2 version

### CODE REVIEW

**Comment by azukov** [comment]
Looking into that. We don't have any test case aside form proton/H- so it's hard to test it.

**Comment by azukov** [comment]
Andrei to provide test file.

**Comment by azukov** [comment]
Actually Juan will do it.

**Comment by azukov** [comment]
@juanfem Juan, I'm a bit confused on this one. Is this ready to merge or you are still preparing [a test that will verify B_rho](https://github.com/orgs/PyORBIT-Collaboration/discussions/11)?

**Comment by juanfem** [comment]
right, I added the test now

**Comment by juanfem** [comment]
@azukov I think this is ready to be merged

**Pull request merged**
